### ISSUE TITLE
Content of the page is not brought

### ISSUE THREAD

**Issue by ghost** [PermanentRecord/mercury-client#1]
Hi,

I'm facing an issue where the module is not bringing the content of the page, but actually, a small session containing `TAGS`, in this link: URL_REDACTED

The content brought by it is the "TAGS", down below the page. Other links do not have it. Is there anything I could do?

**Comment by Meandmybadself** [comment]
@mfgabriel92 – This is just pulling in the content that the Mercury system is returning.  You may want to ping them @ mercury@postlight.com
